[package]
name = "alloy-signer-sm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
alloy-consensus = { workspace = true, features = ["std"] }
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-signer.workspace = true
alloy-sm-sys.workspace = true

thiserror.workspace = true
elliptic-curve = { workspace = true }
eth-keystore = { version = "0.5.0", default-features = false, optional = true }
k256.workspace = true
rand.workspace = true
async-trait.workspace = true

[dev-dependencies]
assert_matches.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true

[features]
keystore = ["dep:eth-keystore"]
